use_frameworks!

platform :ios, '12.0'
install!'cocoapods', :warn_for_unused_master_specs_repo => false

target 'SQLiteORM_Example' do
  pod 'AnyCoder', :path => '../../AnyCoder'
  pod 'SQLiteORM', :path => '../'

  target 'SQLiteORM_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
        end
    end
end
