use_frameworks!

platform :ios, '10.0'
install!'cocoapods', :warn_for_unused_master_specs_repo => false

target 'SQLiteORM_Example' do
  pod 'AnyCoder', :path => '../../AnyCoder'
  pod 'SQLiteORM', :path => '../'

  target 'SQLiteORM_Tests' do
    inherit! :search_paths

    
  end
end
